export const LOAD_POSTS_START = 'LOAD_POSTS_START'
export const LOAD_POSTS_SUCCESS = 'LOAD_POSTS_SUCCESS'
export const LOAD_POSTS_ERROR = 'LOAD_POSTS_ERROR'

export const CREATE_POST_START = 'CREATE_POST_START'
export const CREATE_POST_SUCCESS = 'CREATE_POST_SUCCESS'
export const CREATE_POST_ERROR = 'CREATE_POST_ERROR'

export const  UPDATE_POST_START = 'UPDATE_POST_START'
export const  UPDATE_POST_SUCCESS= 'UPDATE_POST_SUCCESS'
export const  UPDATE_POST_ERROR = 'UPDATE_POST_ERROR'

export const  DELETE_POST_START = 'DELETE_POST_START'
export const  DELETE_POST_SUCCESS= 'DELETE_POST_SUCCESS'
export const  DELETE_POST_ERROR = 'DELETE_POST_ERROR'

